SELECT SEQ , ID , TITLE , REGDATE , DELFLAG , LIKE_USER , HIT_USER 
	FROM ANSWERBOARD a
	WHERE ID='uuser1';
	
SELECT LIKE_USER 
	FROM ANSWERBOARD a 
	WHERE ID='uuser1';
	
SELECT HIT_USER 
	FROM ANSWERBOARD a 
	WHERE ID='uuser1';
	
UPDATE ANSWERBOARD SET LIKE_USER = '{"uuser1":"'||TO_CHAR(SYSDATE,'yyyy-dd-mm')||'"}'
	WHERE SEQ=31;
