CREATE TABLE SPRINGMEMBER(
	ID VARCHAR2(30),
	PW VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(100 NOT NULL,
	AUTH CHAR(1) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "SPRINGMEMBER_PK" PRIMARY KEY(ID),
	CONSTRAINT "SPRINGMEMBER_CK" CHECK("AUTH" IN ('U','A'))
);

CREATE TABLE SPRINGBOARD(
	SEQ NUMBER,
	ID VARCHAR2(30) NOT NULl,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REFERD NUMBER NOT NULL,
	READCOUNT NUMBER,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "SPRINGBOARD_PK" PRIMARY KEY(SEQ),
	CONSTRAINT "SPRINGBOARD_FK" FOREIGN KEY("ID") REFERENCES SPRINGMEMBER("ID")
);

SELECT *
	FROM (
		SELECT SEQ, ID, 
				CASE 
					WHEN STEP>0 
					THEN LPAD(' ', 1+(STEP*6)*3, '&nbsp;') || CONCAT(SUBSTR(TITLE,0.10), '...')
					ELSE TITLE 
					END AS TITLE,
				CONTENT, STEP, DEPTH, "REF", DELFLAG , REGDATE ,
				ROW_NUMBER() OVER(ORDER BY REF DESC, STEP ASC) rn
			FROM ANSWERBOARD a
		)
	WHERE rn BETWEEN 1 AND 5
		AND DELFLAG='N';
		
-- LPAD('값', '총 문자길이', '채움문자')
SELECT CASE 
		WHEN STEP>0 
		THEN LPAD(' ', 1+(STEP*6)*3, '&nbsp;') || CONCAT(SUBSTR(TITLE,0.10), '...')
		ELSE TITLE 
		END AS TITLE
	FROM ANSWERBOARD a ;
	
INSERT INTO HR.ANSWERBOARD
	(SEQ, ID, 
	TITLE, 
	CONTENT, 
	"REF", STEP, "DEPTH", REGDATE, DELFLAG)
	VALUES((SELECT MAX(SEQ)+1 FROM ANSWERBOARD), 'uuser', 
			(SELECT MAX(SEQ)+1 FROM ANSWERBOARD)||' TEST ROOT 글', 
			(SELECT MAX(SEQ)+1 FROM ANSWERBOARD)||' TEST ROOT 내용', 
			(SELECT MAX("REF")+1 FROM ANSWERBOARD), 0, 0, SYSDATE , 'N');
		
SELECT SEQ, ID, TITLE, CONTENT, TO_CHAR(REGDATE, 'YYYY-MM-DD hh24:mi:ss')
	FROM ANSWERBOARD;

-- merge : 10g부터 연속동작이 가능하다 update+delete

UPDATE 
	SET STEP = STEP+1
	WHERE 
		"REF"=(SELECT REF FROM ANSWERBOAR a2 WHERE SEQ='363')
		a.STEP > (SELECT STEP FROM ANSWERBOARD a3 WHERE SEQ='363');

INSERT INTO ANSWERBOARD(SEQ, ID, 
					TITLE, 
					CONTENT, 
					"REF", STEP, "DEPTH", REGDATE, DELFLAG)
		VALUES((SELECT MAX(SEQ)+1 FROM ANSWERBOARD), 'uuser', 
				(SELECT MAX(SEQ)+1 FROM ANSWERBOARD WHERE SEQ='363')||' TEST ROOT 글', 
				(SELECT MAX(SEQ)+1 FROM ANSWERBOARD WHERE SEQ='363')||' TEST ROOT 내용', 
				(SELECT MAX("REF")+1 FROM ANSWERBOARD WHERE SEQ='363'), 0, 0, SYSDATE , 'N');
					
UPDATE ANSWERBOARD 
	SET STEP = STEP + 1
	WHERE REF=(SELECT REF FROM ANSWERBOARD a WHERE SEQ=''),
	STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='');
	
