CREATE TABLE USERINFO(
ID VARCHAR2(30) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
PASSWORD VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
AUTH CHAR(1) NOT NULL,
DELFLAG CHAR(1) NOT NULL,
JOINDATE DATE NOT NULL
);