INSERT INTO HR.USERINFO(ID, NAME, PASSWORD, EMAIL, AUTH, DELFLAG, JOINDATE)
VALUES('', '', '', '', '', '', '');

SELECT ID, NAME, EMAIL, AUTH, DELFLAG, JOINDATE
	FROM(
		SELECT ID, NAME, EMAIL, AUTH, DELFLAG, JOINDATE,
			ROW_NUMBER() OVER(ORDER BY JOINDATE, ID ASC) RN
		FROM USERINFO
		)
	WHERE RN BETWEEN 1 AND 10;